spring:
  ai:
    mcp:
      server:
        name: date-server
        version: 1.0.0
        type: SYNC # 服务器类型（同步/异步）
        instructions: "提供获取不同时区的当前时间，并按照北京时间进行展示"
        sse-message-endpoint: /mcp/messages # 客户端用于发送消息的端点路径,如后续大模型调用工具时，走的就是这个端点
        sse-endpoint: /sse # 用于 Web 传输的自定义 SSE 端点路径，MCP Client主要连接的就是这个端点
        capabilities:
          tool: true # 是否支持工具
          resource: true # 是否支持资源
          prompt: true # 是否支持提示词
          completion: true # 是否支持补全

# 修改日志级别
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
    io.modelcontextprotocol.server.transport.WebMvcSseServerTransportProvider: debug